export const CREAR_EMPLEADO = 'CREAR_EMPLEADO'
export const CREAR_EMPLEADO_EXITO = 'CREAR_EMPLEADO_EXITO'
export const CREAR_EMPLEADO_ERROR = 'CREAR_EMPLEADO_ERROR'

export const LEEER_EMPLEADO = 'LEEER_EMPLEADO'
export const LEEER_EMPLEADO_EXITO = 'LEEER_EMPLEADO_EXITO'
export const LEEER_EMPLEADO_ERROR = 'LEEER_EMPLEADO_ERROR'

export const LOGIN = "LOGIN"
export const LOGIN_EXITO = "LOGIN_EXITO"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT_EXITO = "LOGOUT_EXITO"
