export const CREAR_EMPLEADO = 'CREAR_EMPLEADO'
export const CREAR_EMPLEADO_EXITO = 'CREAR_EMPLEADO_EXITO'
export const CREAR_EMPLEADO_ERROR = 'CREAR_EMPLEADO_ERROR'

export const LEEER_EMPLEADO = 'LEEER_EMPLEADO'
export const LEEER_EMPLEADO_EXITO = 'LEEER_EMPLEADO_EXITO'
export const LEEER_EMPLEADO_ERROR = 'LEEER_EMPLEADO_ERROR'

export const LOGIN = "LOGIN"
export const LOGIN_EXITO = "LOGIN_EXITO"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT_EXITO = "LOGOUT_EXITO"


export const OBTENER_ID = "OBTENER_ID"

export const OBTENER_EMPLEADO_EDITAR = "OBTENER_EMPLEADO_EDITAR"

export const EDITAR_EMPLEADO = 'EDITAR_EMPLEADO'

export const OBTENER_EMPLEADO_ELIMINAR = 'OBTENER_EMPLEADO_ELIMINAR'

export const ELIMINAR_EMPLEADO= 'ELIMINAR_EMPLEADO'

export const CREAR_PROYECTO = 'CREAR_PROYECTO'

export const LEEER_PROYECTO = 'LEEER_PROYECTO'
export const LEEER_PROYECTO_ERROR = 'LEEER_PROYECTO_ERROR'
export const LEEER_PROYECTO_EXITO = 'LEEER_PROYECTO_EXITO'
export const OBTENER_PROYECTO_EDITAR = 'OBTENER_PROYECTO_EDITAR'
export const EDITAR_PROYECTO = 'EDITAR_PROYECTO'
export const OBTENER_PROYECTO_ELIMINAR = 'OBTENER_PROYECTO_ELIMINAR'
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO'


   

